[tool.ufmt]
formatter = "ruff-api"
sorter = "usort"

[tool.usort]
first_party_detection = false
known_first_party = ["torchcomms", "torch"]

[tool.ruff]
line-length = 88

[tool.ruff.format]
# Match internal fbcode settings
